# Manipulação de strings com python

>Uma variável primaria de texto é chamada de char ou caracter, possibilitando o armazenamento de 8 bit de memória.Quando necessitamos de um conjunto de caracteres utilizamos um objeto, ou variáveis compostas no caso da maioria das linguagens chamada de string.Vamos ver como se aplica

In [135]:
frase = "Boa tarde a todos"
print(frase)
saudacao = frase[0:9]
print(saudacao)

Boa tarde a todos
Boa tarde


In [136]:
print(type(frase))
print(type(saudacao))

<class 'str'>
<class 'str'>


In [137]:
print(frase.count(''))
print(saudacao.count(''))

18
10


In [138]:
print(len(frase))
print(len(saudacao))

17
9


In [139]:
frase = frase.replace('a todos','galerinha')
print(frase)
saudacao = saudacao.replace('tarde', 'noite')
print(saudacao)

Boa tarde galerinha
Boa noite


In [140]:
frase = [i for i in frase]
print(frase)

['B', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a']


In [141]:
for x in frase:
    print(x)

B
o
a
 
t
a
r
d
e
 
g
a
l
e
r
i
n
h
a


## Exercise 1

> Faça um código para seguinte frase: "Sabia que o sabiá sabia assobiar" repartição por espaços, depois disso faça um print format para visualizar crie cada palavra em uma coluna separada.

In [142]:
frase2 = "Sabia que o sabiá sabia assobiar"
print(frase2.count(''))
print(frase2.format(''))
palavras = frase2.split()
print(palavras)

for i in range(max(len(x)for x in palavras)):
    for y in palavras:
        print(y[i] if i < len(y) else ' ', end=' ')
    
    print()


33
Sabia que o sabiá sabia assobiar
['Sabia', 'que', 'o', 'sabiá', 'sabia', 'assobiar']
S q o s s a 
a u   a a s 
b e   b b s 
i     i i o 
a     á a b 
          i 
          a 
          r 


# Introdução a Numpy

>Numpy é uma biblioteca python para desenvolvimento de matrizes
>Tem por objetivos facilitar

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.ones((3,3))
print(c)